---
- name: "Docker Image/Build and Image/Push"
  hosts: all
  become: true
  gather_facts: yes

  tasks:

    - name: "Show OS Version"
      debug:
        var: ansible_distribution + " " + ansible_distribution_version


# ansible_host: 192....
